image: Ubuntu2204

environment:
  nodejs_version: "22.15.0"

install:
  - curl -fsSL https://deb.nodesource.com/setup_22.x | sudo -E bash -
  - sudo apt-get install -y nodejs
  - npm install -g npm@11.4.1
  - npm install --include=dev  # Ключевое изменение: ставим и dev-зависимости!

build: off

test_script:
  - node --version
  - npm --version
  - npx jest --coverage --maxWorkers=2  # Используем npx для гарантии

cache:
  - node_modules