image: Ubuntu  # Используем Ubuntu для совместимости

environment:
  nodejs_version: "22.15.0"  # Точно соответствует твоей версии
  NODE_OPTIONS: "--experimental-vm-modules"  # Для поддержки ES-модулей в Jest

install:
  - npm install -g npm@latest  # Обновляем npm до актуальной версии
  - npm install

build: off  # Для JS-проектов сборка не требуется

test_script:
  - node --version
  - npm --version
  - npm test -- --maxWorkers=2 --no-cache  # Отключаем кэш Jest для чистоты тестов

cache:
  - node_modules  # Кэшируем зависимости