image: Ubuntu 22.04  # Используем свежий образ

environment:
  nodejs_version: "22.15.0"  # Точно соответствует твоей версии
  NODE_OPTIONS: "--experimental-vm-modules"

install:
  - corepack enable  # Для корректного управления npm/yarn
  - corepack prepare npm@latest --activate
  - npm install --no-audit

build: off

test_script:
  - node --version
  - npm --version
  - npm test -- --maxWorkers=2

cache:
  - node_modules