image: Ubuntu2204  # Точное имя образа для Ubuntu 22.04

environment:
  nodejs_version: "22.15.0"  # Жёстко фиксируем твою версию

install:
  - curl -fsSL https://deb.nodesource.com/setup_22.x | sudo -E bash -  # Принудительная установка Node 22
  - sudo apt-get install -y nodejs
  - corepack enable
  - npm install -g npm@11.4.1  # Точная версия npm как у тебя

build: off

test_script:
  - node --version
  - npm --version
  - npm test -- --maxWorkers=2

cache:
  - node_modules